services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: athletia
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d athletia -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbs:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: athletia_user_measurements
    volumes:
      - dbs_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d athletia_user_measurements -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
  user_measurements:
    build: ./user_measurements_microservice
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_HOST: dbs
      DB_PORT: '5432'
      DB_NAME: athletia_user_measurements
      DROP_SCHEMA_ON_STARTUP: 'true'
      USERS_SERVICE_URL: http://athletia:3000
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: '5672'
      RABBITMQ_ENABLED: 'true'
      RABBITMQ_PASSWORD: guest
    depends_on:
      dbs:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  recommendations:
    build: ./recomendations_microservice
    ports:
      - "8000:8000"
    environment:
      USERS_SERVICE_URL: http://athletia:3000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  athletia:
    build: ./athletia
    ports:
      - "3000:3000"
    environment:
      user_measurements_MICROSERVICE_URL: http://user_measurements:5000
      RECOMMENDATIONS_SERVICE_URL: http://recommendations:8000
      SERVER_PORT: ${SERVER_PORT}

      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: athletia

      JWT_SECRET_KEY_ACCESS: ${JWT_SECRET_KEY_ACCESS}
      JWT_SECRET_KEY_REFRESH: ${JWT_SECRET_KEY_REFRESH}
      JWT_SECRET_KEY_EMAIL: ${JWT_SECRET_KEY_EMAIL}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: '5672'
      RABBITMQ_ENABLED: 'true'
      RABBITMQ_PASSWORD: guest
    depends_on:
      user_measurements:
        condition: service_healthy
      recommendations:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health-check || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-gateway:
    build: ./api-gateway
    ports:
      - "3001:3001"
    environment:
      ATHLETIA_SERVICE_URL: http://athletia:3000
      SERVER_PORT: ${API_GATEWAY_PORT}
    depends_on:
      athletia:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db_data:
  dbs_data:
  rabbitmq_data:
